linter:
  rules:
    # unnecessary_nullable_for_final_variable_declarations: true
    # avoid_bool_literals_in_conditional_expressions: true
    # avoid_equals_and_hash_code_on_mutable_classes: true
    # avoid_single_cascade_in_expression_statements: true
    # prefer_if_elements_to_conditional_expressions: true
    # missing_whitespace_between_adjacent_strings: true
    # prefer_function_declarations_over_variables: true
    # always_put_required_named_parameters_first: true
    # prefer_const_literals_to_create_immutables: true
    # avoid_field_initializers_in_const_classes: true
    # use_late_for_private_fields_and_variables: true
    # always_require_non_null_named_parameters: true
    # avoid_function_literals_in_foreach_calls: true
    # avoid_null_checks_in_equality_operators: true
    # curly_braces_in_flow_control_structures: true
     prefer_const_constructors_in_immutables: true
    # prefer_constructors_over_static_methods: true
    # prefer_for_elements_to_map_fromIterable: true
    # prefer_interpolation_to_compose_strings: true
    # use_function_type_syntax_for_parameters: true
    # avoid_classes_with_only_static_members: true
    # use_full_hex_values_for_flutter_colors: true
    # leading_newlines_in_multiline_strings: true
    # null_check_on_nullable_type_parameter: true
    # prefer_typing_uninitialized_variables: true
    # unnecessary_null_in_if_null_operators: true
    # use_if_null_to_convert_nulls_to_bools: true
    # avoid_multiple_declarations_per_line: true
    # prefer_adjacent_string_concatenation: true
    # prefer_generic_function_type_aliases: true
    # tighten_type_of_initializing_formals: true
    # always_put_control_body_on_new_line: true
    # avoid_positional_boolean_parameters: true
    # avoid_unused_constructor_parameters: true
    # library_private_types_in_public_api: true
    # prefer_asserts_in_initializer_lists: true
    # unnecessary_brace_in_string_interps: true
    # diagnostic_describe_all_properties: true
    # unnecessary_null_aware_assignments: true
    # avoid_types_on_closure_parameters: true
    # prefer_expression_function_bodies: true
    # unnecessary_string_interpolations: true
    # avoid_catches_without_on_clauses: true
    # avoid_renaming_method_parameters: true
    # iterable_contains_unrelated_type: true
    # literal_only_boolean_expressions: true
    # use_setters_to_change_properties: true
    # avoid_private_typedef_functions: true
    # avoid_redundant_argument_values: true
    # avoid_returning_null_for_future: true
    # avoid_shadowing_type_parameters: true
    # prefer_equal_for_default_values: true
    # sort_unnamed_constructors_first: true
    # use_build_context_synchronously: true
    # avoid_implementing_value_types: true
    # avoid_types_as_parameter_names: true
    # avoid_web_libraries_in_flutter: true
    # package_prefixed_library_names: true
    # prefer_null_aware_method_calls: true
    # unrelated_type_equality_checks: true
    # use_is_even_rather_than_modulo: true
    # use_key_in_widget_constructors: true
    # avoid_annotating_with_dynamic: true
    # avoid_return_types_on_setters: true
    # avoid_returning_null_for_void: true
    # avoid_setters_without_getters: true
    # cast_nullable_to_non_nullable: true
    # depend_on_referenced_packages: true
    # non_constant_identifier_names: true
    # prefer_conditional_assignment: true
    # avoid_unnecessary_containers: true
    # always_declare_return_types: true
    # avoid_double_and_int_checks: true
    # avoid_escaping_inner_quotes: true
    # join_return_with_assignment: true
    # no_adjacent_strings_in_list: true
    # prefer_asserts_with_message: true
    # prefer_initializing_formals: true
    # prefer_null_aware_operators: true
    # provide_deprecation_message: true
    # unnecessary_await_in_return: true
    # unnecessary_getters_setters: true
    # use_to_and_as_if_applicable: true
    # always_use_package_imports: true
    # avoid_relative_lib_imports: true
    # lines_longer_than_80_chars: true
    # list_remove_unrelated_type: true
    # prefer_collection_literals: true
    # sort_child_properties_last: true
    # unnecessary_string_escapes: true
    # constant_identifier_names: true
    # noop_primitive_operations: true
    # omit_local_variable_types: true
     prefer_const_constructors: true
    # prefer_const_declarations: true
    # prefer_iterable_whereType: true
    # prefer_spread_collections: true
    # type_annotate_public_apis: true
    # use_rethrow_when_possible: true
    # empty_constructor_bodies: true
    # no_duplicate_case_values: true
    # no_logic_in_create_state: true
    # prefer_final_in_for_each: true
    # prefer_if_null_operators: true
    # sized_box_for_whitespace: true
    # use_test_throws_matchers: true
    # control_flow_in_finally: true
    # no_runtimeType_toString: true
    # prefer_final_parameters: true
    # prefer_relative_imports: true
    # require_trailing_commas: true
    # sort_constructors_first: true
    # unnecessary_null_checks: true
    # unnecessary_parenthesis: true
    # unnecessary_raw_strings: true
    # deprecated_consistency: true
    # do_not_use_environment: true
    # implementation_imports: true
    # prefer_is_not_operator: true
    # public_member_api_docs: true
    # slash_for_doc_comments: true
    # unnecessary_statements: true
    # avoid_catching_errors: true
    # avoid_js_rounded_ints: true
    # camel_case_extensions: true
    # parameter_assignments: true
    # sort_pub_dependencies: true
    # unnecessary_overrides: true
    # always_specify_types: true
    # avoid_returning_null: true
    # avoid_returning_this: true
    # avoid_type_to_string: true
    # cancel_subscriptions: true
    # one_member_abstracts: true
    # prefer_double_quotes: true
     prefer_single_quotes: true
    # test_types_in_equals: true
    # avoid_dynamic_calls: true
    # avoid_slow_async_io: true
    # cascade_invocations: true
    # directives_ordering: true
    # flutter_style_todos: true
    # prefer_final_fields: true
    # prefer_final_locals: true
    # prefer_inlined_adds: true
    # prefer_int_literals: true
    # prefer_is_not_empty: true
    # prefer_void_to_null: true
    # unnecessary_lambdas: true
    # use_named_constants: true
    # annotate_overrides: true
    # avoid_init_to_null: true
    # await_only_futures: true
    # comment_references: true
    # invariant_booleans: true
    # use_string_buffers: true
    # only_throw_errors: true
    # overridden_fields: true
    # recursive_getters: true
    # type_init_formals: true
    # unawaited_futures: true
    # unnecessary_const: true
    # unnecessary_final: true
    # avoid_empty_else: true
    # avoid_void_async: true
    # camel_case_types: true
    # empty_statements: true
    # exhaustive_cases: true
    # library_prefixes: true
    # no_default_cases: true
    # package_api_docs: true
    # throw_in_finally: true
    # unnecessary_this: true
    # hash_and_equals: true
    # prefer_contains: true
    # prefer_is_empty: true
     unnecessary_new: true
    # use_raw_strings: true
    # prefer_foreach: true
    # empty_catches: true
    # library_names: true
    # null_closures: true
    # package_names: true
    # valid_regexps: true
    # prefer_mixin: true
    #w avoid_print: true
    # close_sinks: true
    # unsafe_html: true
    # void_checks: true
    # file_names: true