targets:
  $default:
    sources:
      - lib/**
    builders:
      json_serializable:
        options:
          include_if_null: false
      artemis:
        options:
          custom_parser_import: lib/time_parser.dart
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
              use_custom_parser: true
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/distribution-network.graphql
              output: lib/dart/distribution-network.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/charge-discharge.graphql
              output: lib/dart/charge-discharge.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/mobile-warehouse.graphql
              output: lib/dart/mobile-warehouse.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/order.graphql
              output: lib/dart/order.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/checkin-activity.graphql
              output: lib/dart/checkin-activity.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/dashboard.graphql
              output: lib/dart/dashboard.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/team-settings.graphql
              output: lib/dart/team-settings.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/pos-visibility.graphql
              output: lib/dart/pos-visibility.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/visibility-classification.graphql
              output: lib/dart/visibility-classification.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/visibility-item.graphql
              output: lib/dart/visibility-item.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/visibility-section.graphql
              output: lib/dart/visibility-section.graphql.dart
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/merch-data.graphql
              output: lib/dart/merch-data.graphql.dart
